import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders

# Configuration
port = 587
smtp_server = "smtp.office365.com"
login = "mohit.mungra@moschip.com"  # Your login generated by Mailtrap
password = "nvkdczbtwdlcbdqh"  # Your password generated by Mailtrap

sender_email = "mohit.mungra@moschip.com"
receiver_email = "mohit.mungra@moschip.com"

# Email content
subject = "Email with Attachment"
body = "Hi,\nThis is a test email with attachment."

# Create a multipart message and set headers
message = MIMEMultipart()
message["From"] = sender_email
message["To"] = receiver_email
message["Subject"] = subject

# Add body to email
message.attach(MIMEText(body, "plain"))

# Specify the attachment file path
filename1 = "report.html"  # Change this to the correct path

# Open the file in binary mode
with open(filename1, "rb") as attachment1:
    part1 = MIMEBase("application", "octet-stream")
    part1.set_payload(attachment1.read())


encoders.encode_base64(part1)
part1.add_header("Content-Disposition", f"attachment; filename= {filename1}")
message.attach(part1)

# Send the email
with smtplib.SMTP(smtp_server, port) as server:
    server.starttls()
    server.login(login, password)
    server.sendmail(sender_email, receiver_email, message.as_string())

print('Sent')
